language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y # for C++14
  - sudo apt-get update
  - sudo apt-get install rustc g++-4.9 openjdk-8-jdk nim
  - sudo ln -f -s /usr/bin/g++-4.9 /usr/bin/g++

install:
  - pip install .
  - pip install flake8 autopep8
  - pip install codecov nose

script:
  - flake8 --ignore=E501, W605
  - autopep8 -r . --exclude 'default_template.py,test_codegen' --diff | tee check_autopep8
  - test ! -s check_autopep8
  - atcoder-tools gen arc050 --without-login
  - nosetests tests --exe -v --with-coverage --cover-package=atcodertools
  - codecov
notifications:
  email: false
