language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r ./requirements.txt
  - pip install flake8 autopep8
  - pip install codecov nose

script:
  - flake8 --ignore=E501, W605
  - autopep8 -r . --diff | tee check_autopep8
  - test ! -s check_autopep8
  - ./atcoder-tools gen arc050 --without-login --no_parallel
  - nosetests --with-coverage --cover-package=atcodertools
  - codecov
notifications:
  email: false
