coverage:
  status:
    project:
      default:
        target: 85%
        threshold: null
        base: auto
    patch:
      default:
        target: 0%
        threshold: null
        base: auto

ignore:
  - "intellij-plugin/src/main/java/atcodertools/intellij/clion"  # Ignore clion package since we are unable to run tests on CI.
