base_indent = 2
global_base_indent = 1
insert_space_around_operators = false

# global変数宣言時の接頭辞
global_prefix = ""

# ループ
[loop]
header = "for(int {loop_var} = 0;{loop_var} < {length};{loop_var}++){{"
footer = "}}"

# タイプ
[type]
int = "long"
float = "double"
string = "string"

# デフォルト値
[default]
int = "long()"
float = "double()"
string = "string()"

# 宣言
[declare]
int = "long {name};"
float = "double {name};"
string = "string {name};"
seq = "{type}[] {name};"
2d_seq = "{type}[,] {name};"

# 確保
[allocate]
seq = "{name} = new {type}[{length}];"
2d_seq = "{name} = new {type}[{length_i},{length_j}];"

# 宣言と確保
[declare_and_allocate]
seq = "{type}[] {name} = new {type}[{length}];"
2d_seq = "{type}[,] {name} = new {type}[{length_i},{length_j}];"

# 入力関数
[input_func]
int = "cin.ReadLong;"
float = "cin.ReadDouble;"
string = "cin.Read;"

# 入力
[input]
int = "{name} = cin.ReadLong;"
float = "{name} = cin.ReadDouble;"
string = "{name} = cin.Read;"

# 引数
[arg]
int = "long {name}"
float = "double {name}"
string = "string {name}"
seq = "{type}[] {name}"
2d_seq = "{type}[,] {name}"

# 配列アクセス
[access]
seq = "{name}[{index_i}]"
2d_seq = "{name}[{index_i},{index_j}]"
